#!/bin/bash
# test_it18_ovpn_server_v2.sh — IT18: openvpn server (tls-crypt-v2) + simple_vpn client
#
# Interoperability test: the reference OpenVPN implementation acts as server
# using tls-crypt-v2, and our simple_vpn client connects using a wrapped
# client key generated by openvpn's own key generation.
#
# Validates cross-implementation tls-crypt-v2 packet format compatibility.
# IT12/IT13 test tls-crypt-v2 with our own server; this is the complement.
#
# Prerequisites:
#   - Root / CAP_NET_ADMIN
#   - openvpn >= 2.6 installed (skips with exit 77 if absent)
#   - simple_vpn built at build/demos/simple_vpn
#   - tls-crypt-v2 keys present (test_data/certs/gen_tls_crypt_v2_keys.sh)
#   - Network namespaces set up via integration/netns/setup_vpn.sh 1
#
# Usage: sudo ./test_it18_ovpn_server_v2.sh [PROJECT_ROOT]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="${1:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
BINARY="${PROJECT_ROOT}/build/demos/simple_vpn"

OVPN_SERVER_CONF="${SCRIPT_DIR}/configs/openvpn/it18_server.conf"
CLIENT_CONFIG="${PROJECT_ROOT}/integration/configs/it_client_v2.json"

NS_SERVER="ns-vpn-server"
NS_CLIENT="ns-vpn-client-0"

TUNNEL_SERVER_IP="10.8.0.1"
SERVER_READY_TIMEOUT=15
HANDSHAKE_TIMEOUT=20
PING_COUNT=5
PING_TIMEOUT=3

LOG_DIR="/tmp/vpn-it18"
SERVER_LOG="${LOG_DIR}/server.log"
CLIENT_LOG="${LOG_DIR}/client.log"

SERVER_PID=""
CLIENT_PID=""

# ── Helpers ──────────────────────────────────────────────────────────

ns_exec() { ip netns exec "$1" "${@:2}"; }
ns_bg()   { exec nsenter --net="/run/netns/$1" -- "${@:2}"; }

cleanup() {
    echo ""
    echo "--- Cleanup ---"
    [[ -n "${CLIENT_PID}" ]] && kill -TERM "${CLIENT_PID}" 2>/dev/null || true
    [[ -n "${SERVER_PID}" ]] && kill -TERM "${SERVER_PID}" 2>/dev/null || true
    sleep 1
    [[ -n "${CLIENT_PID}" ]] && kill -9 "${CLIENT_PID}" 2>/dev/null || true
    [[ -n "${SERVER_PID}" ]] && kill -9 "${SERVER_PID}" 2>/dev/null || true
    wait 2>/dev/null || true
}
trap cleanup EXIT

fail() {
    echo "FAIL: $1"
    echo ""
    echo "--- Server log (last 40 lines) ---"
    tail -40 "${SERVER_LOG}" 2>/dev/null || echo "(no log)"
    echo ""
    echo "--- Client log (last 40 lines) ---"
    tail -40 "${CLIENT_LOG}" 2>/dev/null || echo "(no log)"
    exit 1
}

# ── Preconditions ────────────────────────────────────────────────────

echo "=== IT18: OpenVPN Server (tls-crypt-v2) + simple_vpn Client — Cross-Impl V2 ==="

if [[ $(id -u) -ne 0 ]]; then
    exec sudo --preserve-env=PATH "$0" "$@"
fi

if ! command -v openvpn >/dev/null 2>&1; then
    echo "SKIP: openvpn not found on PATH"
    exit 77
fi

if [[ ! -x "${BINARY}" ]]; then
    echo "Error: Binary not found at ${BINARY}"
    echo "       Run 'ninja -C build' first."
    exit 1
fi

# Verify tls-crypt-v2 key material exists
if [[ ! -f "${PROJECT_ROOT}/test_data/certs/tls-crypt-v2-server.key" ]]; then
    echo "Error: tls-crypt-v2 keys not found."
    echo "       Run test_data/certs/gen_tls_crypt_v2_keys.sh first."
    exit 1
fi

for ns in "${NS_SERVER}" "${NS_CLIENT}"; do
    if ! ip netns list | grep -qw "${ns}"; then
        echo "Error: Namespace ${ns} not found."
        echo "       Run 'sudo integration/netns/setup_vpn.sh 1' first."
        exit 1
    fi
done

mkdir -p "${LOG_DIR}"
rm -f "${SERVER_LOG}" "${CLIENT_LOG}"

cd "${PROJECT_ROOT}"

# ── Start openvpn server (tls-crypt-v2) ──────────────────────────────

echo "[1/6] Starting openvpn server (tls-crypt-v2) in ${NS_SERVER}..."
ns_bg "${NS_SERVER}" openvpn \
    --cd "${PROJECT_ROOT}" \
    --config "${OVPN_SERVER_CONF}" \
    > "${SERVER_LOG}" 2>&1 &
SERVER_PID=$!

server_ready=0
elapsed=0
while (( elapsed < SERVER_READY_TIMEOUT )); do
    if grep -q "Initialization Sequence Completed" "${SERVER_LOG}" 2>/dev/null; then
        server_ready=1
        break
    fi
    if ! kill -0 "${SERVER_PID}" 2>/dev/null; then
        fail "openvpn server exited before initialising"
    fi
    sleep 1
    (( elapsed++ )) || true
done

if (( server_ready == 0 )); then
    fail "openvpn server did not initialise within ${SERVER_READY_TIMEOUT}s"
fi
echo "      openvpn server ready in ~${elapsed}s (PID: ${SERVER_PID})"

# ── Start simple_vpn client with tls-crypt-v2 key ────────────────────

echo "[2/6] Starting simple_vpn client (tls-crypt-v2) in ${NS_CLIENT}..."
ns_bg "${NS_CLIENT}" "${BINARY}" "${CLIENT_CONFIG}" \
    > "${CLIENT_LOG}" 2>&1 &
CLIENT_PID=$!
echo "      Client PID: ${CLIENT_PID}"

# ── Wait for handshake ───────────────────────────────────────────────

echo "[3/6] Waiting up to ${HANDSHAKE_TIMEOUT}s for handshake..."

handshake_ok=0
elapsed=0
while (( elapsed < HANDSHAKE_TIMEOUT )); do
    if grep -qi "client connected\|state.*connected\|connected to server\|PUSH_REPLY.*received\|tunnel established" \
         "${CLIENT_LOG}" 2>/dev/null; then
        handshake_ok=1
        break
    fi
    if ! kill -0 "${SERVER_PID}" 2>/dev/null; then
        fail "openvpn server died during handshake"
    fi
    if ! kill -0 "${CLIENT_PID}" 2>/dev/null; then
        fail "simple_vpn client died during handshake"
    fi
    sleep 1
    (( elapsed++ )) || true
done

if (( handshake_ok == 0 )); then
    fail "Handshake did not complete within ${HANDSHAKE_TIMEOUT}s"
fi
echo "      Handshake completed in ~${elapsed}s"

# ── Ping through tunnel ─────────────────────────────────────────────

echo "[4/6] Pinging openvpn server tunnel IP ${TUNNEL_SERVER_IP} from client..."
sleep 1

if ns_exec "${NS_CLIENT}" ping -c "${PING_COUNT}" -W "${PING_TIMEOUT}" \
    "${TUNNEL_SERVER_IP}" > "${LOG_DIR}/ping.log" 2>&1; then
    echo "      Ping successful (${PING_COUNT}/${PING_COUNT})"
else
    received=$(grep -oP '\d+(?= received)' "${LOG_DIR}/ping.log" || echo "0")
    if (( received > 0 )); then
        echo "      Partial ping success (${received}/${PING_COUNT})"
    else
        fail "Tunnel ping failed — no packets received"
    fi
fi

# ── Collect results ──────────────────────────────────────────────────

echo "[5/6] Collecting results..."
echo ""
echo "--- Ping Results ---"
cat "${LOG_DIR}/ping.log"

# ── Negative validation ─────────────────────────────────────────────

echo ""
echo "[6/6] Negative validation — stopping VPN, confirming tunnel dies..."

kill -TERM "${CLIENT_PID}" 2>/dev/null || true
kill -TERM "${SERVER_PID}" 2>/dev/null || true
sleep 2
kill -9 "${CLIENT_PID}" 2>/dev/null || true
kill -9 "${SERVER_PID}" 2>/dev/null || true
wait 2>/dev/null || true
CLIENT_PID=""
SERVER_PID=""

for ns in "${NS_SERVER}" "${NS_CLIENT}"; do
    for dev in $(ns_exec "$ns" ip -o link show type tun 2>/dev/null | awk -F: '{print $2}' | tr -d ' '); do
        ns_exec "$ns" ip link del "$dev" 2>/dev/null || true
    done
done

if ns_exec "${NS_CLIENT}" ping -c 1 -W 2 "${TUNNEL_SERVER_IP}" &>/dev/null; then
    fail "Tunnel ping succeeded after VPN stopped — traffic may not be using the tunnel"
else
    echo "      Tunnel ping correctly failed after VPN stopped"
fi

echo ""
echo "=== IT18 PASSED ==="
echo "    Logs: ${LOG_DIR}/"
